; [FreeTDS]
; Description=FreeTDS Driver
; Driver=/usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so
; Setup=/usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so


[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/usr/local/lib/libmsodbcsql.17.dylib
UsageCount=1