# Generated by Django 4.1.4 on 2022-12-13 01:05

from django.db import migrations, models
import pandas as pd
from STM.db import DB
from os.path import join
from dotenv import load_dotenv, find_dotenv
load_dotenv()  # Load variables from .env file
dotenv_path = join(find_dotenv())
load_dotenv(dotenv_path)
pd.set_option('display.max_columns', None)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UatEscalation',
            fields=[
                ('escalation_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, unique=True)),
                ('priority', models.IntegerField()),
                ('agent_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('status', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
            ],
            options={
                'db_table': DB.escalation(),
                'managed': False,
            },
        ),
    ]
