# Generated by Django 4.1.4 on 2022-12-19 22:12

import datetimeutc.fields
import django.core.validators
from django.db import migrations, models
import pandas as pd
from STM.db import DB
from os.path import join
from dotenv import load_dotenv, find_dotenv
load_dotenv()  # Load variables from .env file
dotenv_path = join(find_dotenv())
load_dotenv(dotenv_path)
pd.set_option('display.max_columns', None)


class Migration(migrations.Migration):

    dependencies = [
        ('STM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, primary_key=True, serialize=False)),
                ('pein', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': DB.agent(),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('escalation_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, unique=True)),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                # ('targeted_agent', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('submission_dt', datetimeutc.fields.DateTimeUTCField(auto_now_add=True)),
                ('status', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', default='open', max_length=255)),
                ('requestor_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('submission_person_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
            ],
            options={
                'db_table': DB.escalation(),
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UatEscalation',
        ),
    ]
