# Generated by Django 4.1.4 on 2023-01-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STM', '0002_agent_escalation_delete_uatescalation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalation',
            options={},
        ),
    ]
