# Generated by Django 4.1.4 on 2023-06-29 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STM', '0006_alter_escalation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalation',
            options={'managed': False, 'verbose_name': 'Prioritized request'},
        ),
    ]
