# Generated by Django 4.1.4 on 2023-01-20 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STM', '0007_alter_escalation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalation',
            options={'managed': False},
        ),
    ]
