# Generated by Django 4.1.4 on 2024-01-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STM', '0008_alter_escalation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalation',
            options={'managed': False, 'verbose_name': 'Prioritized request'},
        ),
    ]
